name: Integration
# Note requirements below.

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ '**', '!gh-pages', '!coverage' ]
    types: [ opened, reopened, ready_for_review, synchronize ]

jobs:
  
  threshold:
    name: Check Status
    uses: StirlingLabs/Actions/.github/workflows/threshold.yaml@main

  build:
    name: Build
    needs: threshold
    if: |
      needs.threshold.outputs.continue == 'true' && 
      needs.threshold.outputs.release != 'true'
    uses: StirlingLabs/Actions/.github/workflows/dotnetBuild.yaml@main

# Please note that this CI requires:
#
# - Use of https://github.com/StirlingLabs/Version.Net
# - *.Test.csproj contains:
#    <ItemGroup>
#        <PackageReference Include="GitHubActionsTestLogger" Version="2.0.1" PrivateAssets="All" Condition="'$(CI)'!=''" />
#    </ItemGroup>
# - *.csproj contains:
#    <PropertyGroup>
#        <PackageOutputPath Condition="'$(CI)'!=''">../artifacts</PackageOutputPath>
#        <GeneratePackageOnBuild Condition="'$(CI)'!=''">true</GeneratePackageOnBuild>
#    </PropertyGroup>
